services:
  jekyll-site:
    build:
      context: .
      dockerfile: Dockerfile
    # use the bundle-installed jekyll:
    command: ["bash","-lc","bundle exec jekyll serve -H 0.0.0.0 -w --config _config.yml,_config_docker.yml"]
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
    # REMOVE any 'user: 1000:1000' line here (the image already sets USER)

#services:
#  jekyll-site:
#    image: jekyll-site
#    build: .
#    volumes: [ .:/usr/src/app ]
#    ports: [ 4000:4000 ]
#    environment: [ JEKYLL_ENV=docker ]
#    command: jekyll serve -H 0.0.0.0 -w --config _config.yml,_config_docker.yml
